services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/hospital
      PORT: 3000
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16.3
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hospital
      POSTGRES_HOST: postgres