name: CI Pipeline

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 3000:3000

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and tag Docker image
      run: docker build . -t hospital-api

    - name: Run Linting
      run: docker run --rm hospital-api npm run lint

    - name: Run Tests
      run: docker run --rm hospital-api npm run test
    